In [14]:
import torch
import torch.nn as nn
from torch import tensor
import torch.nn.functional as F

### Simple Call

In [2]:
relu = nn.ReLU()

x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6., -1]
    ]
])

relu(x)

tensor([[[1., 2., 3., 4., 5., 6., 0.]]])

In [3]:
for p in relu.parameters():
    print(p)

In [16]:
F.relu(tensor([1,-2]))

tensor([1, 0])

### Grad

In [10]:
model = nn.Sequential(
    nn.Linear(1, 2, bias=False),
    nn.ReLU(),
    nn.Linear(2, 1, bias=False)
)

state_dict = {
    "0.weight": torch.tensor([
        [-1.],
        [2.]
    ]),
    
    "2.weight": torch.tensor([
        [3., 4.]
    ])
}

model.load_state_dict(state_dict)

x = tensor([1.])
y = model(x)
print("y:", y)

loss_fn = nn.MSELoss()
target = tensor([10.])

loss = loss_fn(y, target)
print("loss:", loss)

loss.backward()

y: tensor([8.], grad_fn=<SqueezeBackward4>)
loss: tensor(4., grad_fn=<MseLossBackward0>)


In [11]:
model[0].weight.grad

tensor([[  0.],
        [-16.]])

In [13]:
model[2].weight.grad

tensor([[ 0., -8.]])

In [18]:
w_layer0_0 = tensor(-1)
w_layer0_1 = tensor(2)

w_layer2_0 = tensor(3)
w_layer2_1 = tensor(4)

x = tensor(1)

y = (F.relu(tensor([ x * w_layer0_0 , x * w_layer0_1 ])) * tensor([w_layer2_0 , w_layer2_1])).sum()
y

tensor(8)

In [26]:
y = x * w_layer0_1 * w_layer2_1
y

tensor(8)

In [27]:
target = 10
L = (y - target) ** 2
dL_dy = 2 * (y - target)

dy_dw_layer2_1 = x * w_layer0_1

dL_dw_layer2_1 = dL_dy * dy_dw_layer2_1
dL_dw_layer2_1

tensor(-8)

In [28]:
dy_dw_layer2_0 = 0
dy_dw_layer2_0

0

In [29]:
dL_dw_layer2_0 = dL_dy * dy_dw_layer2_0
dL_dw_layer2_0

tensor(0)