## Simple Use

In [1]:
import torch
import torch.nn as nn
from torch import tensor

### Simple

In [23]:
rnn = nn.RNN(
    input_size=1,
    hidden_size=1,
    bias=False,
    batch_first=True
)

In [24]:
for name, p in rnn.named_parameters():
    print(name, p)

weight_ih_l0 Parameter containing:
tensor([[-0.1085]], requires_grad=True)
weight_hh_l0 Parameter containing:
tensor([[0.3633]], requires_grad=True)


In [32]:
state_dict = {
    "weight_ih_l0": torch.tensor([
        [3.]
    ]),
    "weight_hh_l0": torch.tensor([
        [4.]
    ])
}
rnn.load_state_dict(state_dict)

<All keys matched successfully>

In [33]:
for name, p in rnn.named_parameters():
    print(name, p)

weight_ih_l0 Parameter containing:
tensor([[3.]], requires_grad=True)
weight_hh_l0 Parameter containing:
tensor([[4.]], requires_grad=True)


In [34]:
x = torch.tensor([
    [
        [1.0],
    ]
])
x.shape

torch.Size([1, 1, 1])

In [35]:
output, hidden = rnn(x)

In [36]:
output, hidden

(tensor([[[0.9951]]], grad_fn=<TransposeBackward1>),
 tensor([[[0.9951]]], grad_fn=<StackBackward0>))

In [37]:
W_ih = 3
W_hh = 4

x_1 = 1.0
h_0 = 0

In [38]:
x_1 * W_ih + h_0 * W_hh

3.0

In [39]:
torch.tanh(torch.tensor(3))

tensor(0.9951)

In [40]:
e_2y = torch.exp(tensor(2. * 3.))
e_2y

tensor(403.4288)

In [41]:
tanh_y = (e_2y - 1)/(e_2y + 1)
tanh_y

tensor(0.9951)

In [43]:
### Relu
rnn = nn.RNN(
    input_size=1,
    hidden_size=1,
    bias=False,
    batch_first=True,
    nonlinearity="relu"
)
state_dict = {
    "weight_ih_l0": torch.tensor([
        [3.]
    ]),
    "weight_hh_l0": torch.tensor([
        [4.]
    ])
}
rnn.load_state_dict(state_dict)

x = torch.tensor([
    [
        [1.0],
    ]
])

output, hidden = rnn(x)
output, hidden

(tensor([[[3.]]], grad_fn=<TransposeBackward1>),
 tensor([[[3.]]], grad_fn=<StackBackward0>))

In [44]:
### Default tanh
rnn = nn.RNN(
    input_size=1,
    hidden_size=1,
    bias=False,
    batch_first=True,
)
state_dict = {
    "weight_ih_l0": torch.tensor([
        [3.]
    ]),
    "weight_hh_l0": torch.tensor([
        [4.]
    ])
}
rnn.load_state_dict(state_dict)

x = torch.tensor([
    [
        [1.0],
    ]
])

output, hidden = rnn(x)
output, hidden

(tensor([[[0.9951]]], grad_fn=<TransposeBackward1>),
 tensor([[[0.9951]]], grad_fn=<StackBackward0>))

In [51]:
### Default bacth 5
rnn = nn.RNN(
    input_size=1,
    hidden_size=1,
    bias=False,
    batch_first=True,
)
state_dict = {
    "weight_ih_l0": torch.tensor([
        [3.]
    ]),
    "weight_hh_l0": torch.tensor([
        [4.]
    ])
}
rnn.load_state_dict(state_dict)

x = torch.tensor([
    [[0.1],],
    [[0.2],],
    [[0.3],],
    [[0.4],],
    [[0.5],],
])

In [52]:
x.shape

torch.Size([5, 1, 1])

In [53]:
output, hidden = rnn(x)
output.shape 

torch.Size([5, 1, 1])

In [54]:
hidden.shape

torch.Size([1, 5, 1])

In [55]:
output

tensor([[[0.2913]],

        [[0.5370]],

        [[0.7163]],

        [[0.8337]],

        [[0.9051]]], grad_fn=<TransposeBackward1>)

In [56]:
hidden

tensor([[[0.2913],
         [0.5370],
         [0.7163],
         [0.8337],
         [0.9051]]], grad_fn=<StackBackward0>)

In [72]:
### Seq Length > 1
rnn = nn.RNN(
    input_size=1,
    hidden_size=1,
    bias=False,
    batch_first=True,
)
state_dict = {
    "weight_ih_l0": torch.tensor([
        [3.]
    ]),
    "weight_hh_l0": torch.tensor([
        [4.]
    ])
}
rnn.load_state_dict(state_dict)

x = torch.tensor([
    [[0.1], [0.2]],
])

output, hidden = rnn(x)
output, hidden

(tensor([[[0.2913],
          [0.9431]]], grad_fn=<TransposeBackward1>),
 tensor([[[0.9431]]], grad_fn=<StackBackward0>))

In [73]:
W_ih = rnn.weight_ih_l0.item()
W_hh = rnn.weight_hh_l0.item()

print(W_ih)
print(W_hh)

3.0
4.0


In [74]:
h0 = 0

x1 = 0.1
x2 = 0.2

In [75]:
z1 = torch.tensor(x1 * W_ih + h0 * W_hh)
z1

tensor(0.3000)

In [76]:
h1 = torch.tanh(z1)
h1

tensor(0.2913)

In [77]:
z2 = torch.tensor(x2 * W_ih + h1.item() * W_hh)
z2

tensor(1.7653)

In [78]:
h2 = torch.tanh(z2)
h2

tensor(0.9431)

In [79]:
### Seq Length > 1, batch > 1
rnn = nn.RNN(
    input_size=1,
    hidden_size=1,
    bias=False,
    batch_first=True,
)
state_dict = {
    "weight_ih_l0": torch.tensor([
        [3.]
    ]),
    "weight_hh_l0": torch.tensor([
        [4.]
    ])
}
rnn.load_state_dict(state_dict)

x = torch.tensor([
    [[0.1], [0.2]],
    [[0.2], [0.3]],
    [[0.3], [0.4]],
])

output, hidden = rnn(x)
output.shape, hidden.shape

(torch.Size([3, 2, 1]), torch.Size([1, 3, 1]))

In [80]:
### Hidden Size > 1
rnn = nn.RNN(
    input_size=1,
    hidden_size=2,
    bias=False,
    batch_first=True,
)

state_dict = {
    "weight_ih_l0": torch.tensor([
        [3.],
        [5.]
    ]),
    "weight_hh_l0": torch.tensor([
        [4., 6.],
        [7., 8.]
    ])
}
rnn.load_state_dict(state_dict)

<All keys matched successfully>

In [81]:
x = torch.tensor([
    [[0.1]],
])

output, hidden = rnn(x)

In [82]:
output.shape, hidden.shape

(torch.Size([1, 1, 2]), torch.Size([1, 1, 2]))

In [87]:
output

tensor([[[0.2913, 0.4621]]], grad_fn=<TransposeBackward1>)

In [83]:
W_ih = rnn.weight_ih_l0
W_hh = rnn.weight_hh_l0

print(W_ih)
print(W_hh)

Parameter containing:
tensor([[3.],
        [5.]], requires_grad=True)
Parameter containing:
tensor([[4., 6.],
        [7., 8.]], requires_grad=True)


In [88]:
h0 = torch.tensor([0., 0.])
x1 = torch.tensor([0.1])
x2 = torch.tensor([0.2])

In [89]:
z1 = (W_ih @ x1) + (W_hh @ h0)
z1

tensor([0.3000, 0.5000], grad_fn=<AddBackward0>)

In [90]:
h1 = torch.tanh(z1)
h1

tensor([0.2913, 0.4621], grad_fn=<TanhBackward0>)

In [93]:
### Hidden Size > 1, Seq Length > 1
rnn = nn.RNN(
    input_size=1,
    hidden_size=2,
    bias=False,
    batch_first=True,
)

state_dict = {
    "weight_ih_l0": torch.tensor([
        [0.3],
        [0.5]
    ]),
    "weight_hh_l0": torch.tensor([
        [0.4, 0.6],
        [0.7, 0.8]
    ])
}
rnn.load_state_dict(state_dict)

x = torch.tensor([
    [[0.1], [0.2], [0.3], [0.4]],
])

output, hidden = rnn(x)

In [94]:
output

tensor([[[0.0300, 0.0500],
         [0.1016, 0.1596],
         [0.2226, 0.3353],
         [0.3887, 0.5540]]], grad_fn=<TransposeBackward1>)

In [95]:
W_ih = rnn.weight_ih_l0
W_hh = rnn.weight_hh_l0

print(W_ih)
print(W_hh)

Parameter containing:
tensor([[0.3000],
        [0.5000]], requires_grad=True)
Parameter containing:
tensor([[0.4000, 0.6000],
        [0.7000, 0.8000]], requires_grad=True)


In [101]:
h0 = torch.tensor([0., 0.])
x1 = torch.tensor([0.1])
x2 = torch.tensor([0.2])
x3 = torch.tensor([0.3])
x4 = torch.tensor([0.4])

In [97]:
z1 = (W_ih @ x1) + (W_hh @ h0)
z1

tensor([0.0300, 0.0500], grad_fn=<AddBackward0>)

In [98]:
h1 = torch.tanh(z1)
h1

tensor([0.0300, 0.0500], grad_fn=<TanhBackward0>)

In [100]:
z2 = (W_ih @ x2) + (W_hh @ h1)
h2 = torch.tanh(z2)
h2

tensor([0.1016, 0.1596], grad_fn=<TanhBackward0>)

In [102]:
z3 = (W_ih @ x3) + (W_hh @ h2)
h3 = torch.tanh(z3)
h3

tensor([0.2226, 0.3353], grad_fn=<TanhBackward0>)

In [103]:
z4 = (W_ih @ x4) + (W_hh @ h3)
h4 = torch.tanh(z4)
h4

tensor([0.3887, 0.5540], grad_fn=<TanhBackward0>)

In [104]:
### Hidden Size > 1, Seq Length > 1, Batch > 1
rnn = nn.RNN(
    input_size=1,
    hidden_size=2,
    bias=False,
    batch_first=True,
)

state_dict = {
    "weight_ih_l0": torch.tensor([
        [0.3],
        [0.5]
    ]),
    "weight_hh_l0": torch.tensor([
        [0.4, 0.6],
        [0.7, 0.8]
    ])
}
rnn.load_state_dict(state_dict)

x = torch.tensor([
    [[0.1], [0.2], [0.3], [0.4]],
    [[0.1], [0.2], [0.3], [0.4]],
    [[0.1], [0.2], [0.3], [0.4]],
    [[0.1], [0.2], [0.3], [0.4]],
    [[0.1], [0.2], [0.3], [0.4]],
    [[0.1], [0.2], [0.3], [0.4]],
    [[0.1], [0.2], [0.3], [0.4]],
])

output, hidden = rnn(x)

In [105]:
output.shape, hidden.shape

(torch.Size([7, 4, 2]), torch.Size([1, 7, 2]))