In [1]:
import torch
import torch.nn as nn
from torch import tensor

In [9]:
# Seq Length = 0
rnn = nn.RNN(
    input_size=1,
    hidden_size=1,
    bias=False,
    bidirectional=True,
    batch_first=True
)

state_dict = {
    # Forward
    "weight_ih_l0": torch.tensor([
        [0.3]
    ]),
    "weight_hh_l0": torch.tensor([
        [0.4]
    ]),

    # Backward
    "weight_ih_l0_reverse": torch.tensor([
        [0.5]
    ]),
    "weight_hh_l0_reverse": torch.tensor([
        [0.6]
    ])
}
rnn.load_state_dict(state_dict)

<All keys matched successfully>

In [10]:
x = torch.tensor([
    [
        [0.1],
    ]
])
x.shape

torch.Size([1, 1, 1])

In [11]:
output, hidden = rnn(x)
output, hidden

(tensor([[[0.0300, 0.0500]]], grad_fn=<TransposeBackward1>),
 tensor([[[0.0300]],
 
         [[0.0500]]], grad_fn=<StackBackward0>))

In [12]:
output.shape, hidden.shape

(torch.Size([1, 1, 2]), torch.Size([2, 1, 1]))

In [15]:
W_ih = rnn.weight_ih_l0.item()
W_hh = rnn.weight_hh_l0.item()

h0 = 0
x1 = 0.1

z1 = torch.tensor(x1 * W_ih + h0 * W_hh)
h1 = torch.tanh(z1)
h1

tensor(0.0300)

In [27]:
W_ih_reverse = rnn.weight_ih_l0_reverse.item()
W_hh_reverse = rnn.weight_hh_l0_reverse.item()

h0_reverse = 0

x1 = 0.1

z1_reverse = torch.tensor(x1 * W_ih_reverse + h0_reverse * W_hh_reverse)
h1_reverse = torch.tanh(z1_reverse)
h1_reverse

tensor(0.0500)

In [20]:
# Seq Length > 1
x = torch.tensor([
    [
        [0.1], [0.2], [0.3],
    ]
])
x.shape

torch.Size([1, 3, 1])

In [21]:
output, hidden = rnn(x)
output, hidden

(tensor([[[0.0300, 0.1609],
          [0.0719, 0.1871],
          [0.1182, 0.1489]]], grad_fn=<TransposeBackward1>),
 tensor([[[0.1182]],
 
         [[0.1609]]], grad_fn=<StackBackward0>))

In [22]:
output.shape, hidden.shape

(torch.Size([1, 3, 2]), torch.Size([2, 1, 1]))

In [26]:
W_ih = rnn.weight_ih_l0.item()
W_hh = rnn.weight_hh_l0.item()

h0 = 0
x1 = 0.1
x2 = 0.2
x3 = 0.3

z1 = torch.tensor(x1 * W_ih + h0 * W_hh)
h1 = torch.tanh(z1)

z2 = torch.tensor(x2 * W_ih + h1.item() * W_hh)
h2 = torch.tanh(z2)

z3 = torch.tensor(x3 * W_ih + h2.item() * W_hh)
h3 = torch.tanh(z3)

print(h1, h2, h3)

tensor(0.0300) tensor(0.0719) tensor(0.1182)


In [28]:
W_ih_reverse = rnn.weight_ih_l0_reverse.item()
W_hh_reverse = rnn.weight_hh_l0_reverse.item()

h0_reverse = 0

x1 = 0.1
x2 = 0.2
x3 = 0.3

z3_reverse = torch.tensor(
    x3 * W_ih_reverse + h0_reverse * W_hh_reverse
)
h3_reverse = torch.tanh(z3_reverse)

z2_reverse = torch.tensor(
    x2 * W_ih_reverse + h3_reverse.item() * W_hh_reverse
)
h2_reverse = torch.tanh(z2_reverse)

z1_reverse = torch.tensor(
    x1 * W_ih_reverse + h2_reverse.item() * W_hh_reverse
)
h1_reverse = torch.tanh(z1_reverse)

print(h1_reverse, h2_reverse, h3_reverse)

tensor(0.1609) tensor(0.1871) tensor(0.1489)


In [29]:
output, hidden

(tensor([[[0.0300, 0.1609],
          [0.0719, 0.1871],
          [0.1182, 0.1489]]], grad_fn=<TransposeBackward1>),
 tensor([[[0.1182]],
 
         [[0.1609]]], grad_fn=<StackBackward0>))