In [1]:
import torch
import torch.nn as nn
from torch import tensor

### Simple

In [2]:
x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6.]
    ]
])

In [6]:
conv = nn.Conv1d(
    in_channels=1,
    out_channels=1,
    kernel_size=1,
    bias=False
)
state_dict = {
    "weight": torch.tensor([
        [[2.]]
    ])
}
conv.load_state_dict(state_dict)

<All keys matched successfully>

In [7]:
conv.weight

Parameter containing:
tensor([[[2.]]], requires_grad=True)

In [8]:
y = conv(x)
y

tensor([[[ 2.,  4.,  6.,  8., 10., 12.]]], grad_fn=<ConvolutionBackward0>)

In [9]:
y.shape

torch.Size([1, 1, 6])

In [10]:
tensor([1., 2., 3., 4., 5., 6.]) * tensor(2.0)

tensor([ 2.,  4.,  6.,  8., 10., 12.])

### Out Channels

In [11]:
x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6.]
    ]
])

In [12]:
conv = nn.Conv1d(
    in_channels=1,
    out_channels=2,
    kernel_size=1,
    bias=False
)

state_dict = {
    "weight": torch.tensor([
        [[2.]],
        [[3.]]
    ])
}
conv.load_state_dict(state_dict)

<All keys matched successfully>

In [13]:
conv.weight

Parameter containing:
tensor([[[2.]],

        [[3.]]], requires_grad=True)

In [14]:
y = conv(x)
y

tensor([[[ 2.,  4.,  6.,  8., 10., 12.],
         [ 3.,  6.,  9., 12., 15., 18.]]], grad_fn=<ConvolutionBackward0>)

In [15]:
tensor([1., 2., 3., 4., 5., 6.]) * tensor(2.0)

tensor([ 2.,  4.,  6.,  8., 10., 12.])

In [16]:
tensor([1., 2., 3., 4., 5., 6.]) * tensor(3.0)

tensor([ 3.,  6.,  9., 12., 15., 18.])

### Kernel Size

In [17]:
x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6.]
    ]
])
conv = nn.Conv1d(
    in_channels=1,
    out_channels=1,
    kernel_size=2,
    bias=False
)

state_dict = {
    "weight": torch.tensor([
        [
            [2., 3.]
        ]
    ])
}
conv.load_state_dict(state_dict)

<All keys matched successfully>

In [18]:
conv.weight

Parameter containing:
tensor([[[2., 3.]]], requires_grad=True)

In [19]:
y = conv(x)
y

tensor([[[ 8., 13., 18., 23., 28.]]], grad_fn=<ConvolutionBackward0>)

In [20]:
(tensor([1., 2.]) * tensor([2., 3.])).sum()

tensor(8.)

In [21]:
(tensor([ 2., 3.]) * tensor([2., 3.])).sum()

tensor(13.)

### Bias

In [24]:
x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6.]
    ]
])

conv = nn.Conv1d(
    in_channels=1,
    out_channels=1,
    kernel_size=1,
    bias=True
)

state_dict = {
    "weight": torch.tensor([
        [
            [2.]
        ]
    ]),
    "bias": torch.tensor([
        10.
    ])
}

conv.load_state_dict(state_dict)

<All keys matched successfully>

In [25]:
conv.weight, conv.bias

(Parameter containing:
 tensor([[[2.]]], requires_grad=True),
 Parameter containing:
 tensor([10.], requires_grad=True))

In [26]:
y = conv(x)
y

tensor([[[12., 14., 16., 18., 20., 22.]]], grad_fn=<ConvolutionBackward0>)

In [28]:
tensor([1., 2., 3., 4., 5., 6.]) * tensor(2.) + tensor(10.)

tensor([12., 14., 16., 18., 20., 22.])

### Input Channels

In [29]:
x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6.],
        [4., 5., 6., 7., 8., 9.],
    ]
])
conv = nn.Conv1d(
    in_channels=2,
    out_channels=1,
    kernel_size=1,
    bias=False
)
state_dict = {
    "weight": torch.tensor([
        [
            [2.],
            [3.]
        ]
    ])
}

conv.load_state_dict(state_dict)

<All keys matched successfully>

In [30]:
conv.weight

Parameter containing:
tensor([[[2.],
         [3.]]], requires_grad=True)

In [31]:
y = conv(x)
y

tensor([[[14., 19., 24., 29., 34., 39.]]], grad_fn=<ConvolutionBackward0>)

In [32]:
tensor([1., 2., 3., 4., 5., 6.]) * tensor(2.0)

tensor([ 2.,  4.,  6.,  8., 10., 12.])

In [33]:
tensor([4., 5., 6., 7., 8., 9.]) * tensor(3.0)

tensor([12., 15., 18., 21., 24., 27.])

In [34]:
tensor([ 2.,  4.,  6.,  8., 10., 12.]) + tensor([12., 15., 18., 21., 24., 27.])

tensor([14., 19., 24., 29., 34., 39.])

### Padding

In [40]:
x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6.]
    ]
])
conv = nn.Conv1d(
    in_channels=1,
    out_channels=1,
    kernel_size=2,
    bias=False,
    padding=1
)

state_dict = {
    "weight": torch.tensor([
        [
            [2., 3.]
        ]
    ])
}
conv.load_state_dict(state_dict)

<All keys matched successfully>

In [41]:
conv.weight

Parameter containing:
tensor([[[2., 3.]]], requires_grad=True)

In [42]:
y = conv(x)
y

tensor([[[ 3.,  8., 13., 18., 23., 28., 12.]]], grad_fn=<ConvolutionBackward0>)

In [44]:
(tensor([0., 1.]) * tensor([2., 3.])).sum()

tensor(3.)

In [43]:
(tensor([1., 2.]) * tensor([2., 3.])).sum()

tensor(8.)

In [45]:
(tensor([5., 6.]) * tensor([2., 3.])).sum()

tensor(28.)

In [46]:
(tensor([6., 0.]) * tensor([2., 3.])).sum()

tensor(12.)

### Padding Same

In [50]:
x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6.]
    ]
])
conv = nn.Conv1d(
    in_channels=1,
    out_channels=1,
    kernel_size=2,
    bias=False,
    padding="same"
)

state_dict = {
    "weight": torch.tensor([
        [
            [2., 3.]
        ]
    ])
}
conv.load_state_dict(state_dict)

<All keys matched successfully>

In [51]:
conv.weight

Parameter containing:
tensor([[[2., 3.]]], requires_grad=True)

In [52]:
y = conv(x)
y

/home/ridwanfatur/miniconda3/envs/py3_12_9/lib/python3.12/site-packages/torch/nn/modules/conv.py:380: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at /__w/pytorch/pytorch/aten/src/ATen/native/Convolution.cpp:1101.)
  return F.conv1d(


tensor([[[ 8., 13., 18., 23., 28., 12.]]], grad_fn=<ConvolutionBackward0>)

In [53]:
(tensor([1., 2.]) * tensor([2, 3])).sum()

tensor(8.)

In [54]:
(tensor([6., 0.]) * tensor([2, 3])).sum()

tensor(12.)

### Stride

In [55]:
x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6.]
    ]
])
conv = nn.Conv1d(
    in_channels=1,
    out_channels=1,
    kernel_size=2,
    bias=False,
    stride=2
)

state_dict = {
    "weight": torch.tensor([
        [
            [2., 3.]
        ]
    ])
}
conv.load_state_dict(state_dict)

<All keys matched successfully>

In [56]:
conv.weight

Parameter containing:
tensor([[[2., 3.]]], requires_grad=True)

In [57]:
y = conv(x)
y

tensor([[[ 8., 18., 28.]]], grad_fn=<ConvolutionBackward0>)

In [58]:
(tensor([1., 2.]) * tensor([2,3])).sum()

tensor(8.)

In [59]:
(tensor([3., 4]) * tensor([2,3])).sum()

tensor(18.)

In [60]:
(tensor([5., 6.]) * tensor([2,3])).sum()

tensor(28.)

### Grad

In [62]:
x = torch.tensor([
    [
        [1., 2., 3., 4., 5., 6.]
    ]
])
conv = nn.Conv1d(
    in_channels=1,
    out_channels=1,
    kernel_size=2,
    bias=False,
    stride=2
)

state_dict = {
    "weight": torch.tensor([
        [
            [2., 3.]
        ]
    ])
}
conv.load_state_dict(state_dict)

<All keys matched successfully>

In [64]:
y_pred = conv(x)
y_pred

tensor([[[ 8., 18., 28.]]], grad_fn=<ConvolutionBackward0>)

In [65]:
y_target = tensor([[[ 10., 15., 30.]]])

In [66]:
loss_fn = nn.MSELoss()

loss = loss_fn(y_pred, y_target)
loss

tensor(5.6667, grad_fn=<MseLossBackward0>)

In [67]:
loss.backward()

In [68]:
conv.weight.grad

tensor([[[-2.0000, -2.6667]]])

In [71]:
w0 = tensor(2.0)
w1 = tensor(3.0)

x0 = tensor(1.)
x1 = tensor(2.)
x2 = tensor(3.)
x3 = tensor(4.)
x4 = tensor(5.)
x5 = tensor(6.)

y_pred0 = x0 * w0 + x1 * w1
y_pred1 = x2 * w0 + x3 * w1
y_pred2 = x4 * w0 + x5 * w1

y_target0 = tensor(10.)
y_target1 = tensor(15.)
y_target2 = tensor(30.)

L0 = (y_pred0 - y_target0) ** 2
L1 = (y_pred1 - y_target1) ** 2
L2 = (y_pred2 - y_target2) ** 2

L = (L0 + L1 + L2) / 3

dL0_dypred0 = 2 * (y_pred0 - y_target0)
dL1_dypred1 = 2 * (y_pred1 - y_target1)
dL2_dypred2 = 2 * (y_pred2 - y_target2)

In [72]:
dypred0_dw0 = x0
dypred1_dw0 = x2
dypred2_dw0 = x4

dL0_dw0 = dL0_dypred0 * dypred0_dw0
dL1_dw0 = dL1_dypred1 * dypred1_dw0
dL2_dw0 = dL2_dypred2 * dypred2_dw0

dL_dw0 = (dL0_dw0 + dL1_dw0 + dL2_dw0) / 3
dL_dw0

tensor(-2.)

In [73]:
dypred0_dw1 = x1
dypred1_dw1 = x3
dypred2_dw1 = x5

dL0_dw1 = dL0_dypred0 * dypred0_dw1
dL1_dw1 = dL1_dypred1 * dypred1_dw1
dL2_dw1 = dL2_dypred2 * dypred2_dw1

dL_dw1 = (dL0_dw1 + dL1_dw1 + dL2_dw1) / 3
dL_dw1

tensor(-2.6667)