In [70]:
from torch import tensor, nn
import torch

### Use nn Linear

In [2]:
model = nn.Linear(2,3)

In [3]:
model.weight

Parameter containing:
tensor([[-0.1170,  0.1165],
        [ 0.0605, -0.5389],
        [-0.1216, -0.1630]], requires_grad=True)

In [4]:
model.bias

Parameter containing:
tensor([ 0.3833, -0.4404, -0.4483], requires_grad=True)

In [13]:
x = tensor([1.0,2.0])

In [17]:
x.shape

torch.Size([2])

In [15]:
y = model(x)

In [16]:
y.shape

torch.Size([3])

In [18]:
x = tensor([
    [1.0,2.0],
    [1.0,2.0],
])

In [19]:
x.shape

torch.Size([2, 2])

In [20]:
y = model(x)

In [21]:
y.shape

torch.Size([2, 3])

In [22]:
y

tensor([[ 0.4992, -1.4578, -0.8958],
        [ 0.4992, -1.4578, -0.8958]], grad_fn=<AddmmBackward0>)

### Manual Linear

In [23]:
model = nn.Linear(1,1)

In [24]:
model.weight, model.bias

(Parameter containing:
 tensor([[-0.1251]], requires_grad=True),
 Parameter containing:
 tensor([-0.9759], requires_grad=True))

In [27]:
x = tensor([2.0])
y = model(x)
y

tensor([-1.2261], grad_fn=<ViewBackward0>)

In [28]:
2.0 * -0.1251 + -0.9759

-1.2261

In [29]:
x = tensor([3.0])
y = model(x)
y

tensor([-1.3512], grad_fn=<ViewBackward0>)

In [30]:
3.0 * -0.1251 + -0.9759

-1.3512

In [31]:
model = nn.Linear(4,1)

In [33]:
model.weight, model.bias

(Parameter containing:
 tensor([[ 0.0538, -0.0048,  0.0616,  0.1770]], requires_grad=True),
 Parameter containing:
 tensor([0.2112], requires_grad=True))

In [34]:
x = tensor([1.0, 2.0, 3.0, 4.0])
y = model(x)
y

tensor([1.1484], grad_fn=<ViewBackward0>)

In [38]:
(tensor([1.0, 2.0, 3.0, 4.0]) * tensor([ 0.0538, -0.0048,  0.0616,  0.1770])).sum() + 0.2112

tensor(1.1482)

In [40]:
model = nn.Linear(3,2)

In [41]:
model.weight, model.bias

(Parameter containing:
 tensor([[ 0.4236, -0.5029, -0.5649],
         [-0.4842, -0.1089, -0.3735]], requires_grad=True),
 Parameter containing:
 tensor([-0.4850, -0.3166], requires_grad=True))

In [42]:
x = tensor([1.0, 2.0, 3.0])
y = model(x)
y

tensor([-2.7618, -2.1390], grad_fn=<ViewBackward0>)

In [43]:
(tensor([ 0.4236, -0.5029, -0.5649]) * tensor([ 1.0, 2.0, 3.0 ])).sum() + -0.4850

tensor(-2.7619)

In [44]:
(tensor([ -0.4842, -0.1089, -0.3735]) * tensor([ 1.0, 2.0, 3.0 ])).sum() + -0.3166

tensor(-2.1391)

### Sequential

In [48]:
model = nn.Sequential(
    nn.Linear(5, 6),
    nn.Linear(6, 1),
)

In [49]:
x = tensor([1.0, 2.0, 3.0, 4.0, 5.0])
y = model(x)
y

tensor([0.0835], grad_fn=<ViewBackward0>)

In [50]:
layer_1 = model[0]
layer_2 = model[1]

In [51]:
x = tensor([1.0, 2.0, 3.0, 4.0, 5.0])
temp = layer_1(x)
temp

tensor([-0.7207,  2.6929,  1.4313, -1.0688, -1.9611, -0.8306],
       grad_fn=<ViewBackward0>)

In [52]:
y = layer_2(temp)
y

tensor([0.0835], grad_fn=<ViewBackward0>)

### Loss Function

In [53]:
loss_fn = nn.MSELoss()

In [55]:
y_pred = tensor([10.0])
y_true = tensor([1.0])

In [57]:
loss_fn(y_pred, y_true)

tensor(81.)

In [56]:
((10 - 1) ** 2)/1

81.0

In [58]:
y_pred = tensor([10.0, 8.0])
y_true = tensor([1.0, 7.0])

In [59]:
loss_fn(y_pred, y_true)

tensor(41.)

In [60]:
((10 - 1) ** 2 + (8 - 7) ** 2)/2

41.0

### Update Weight

In [84]:
torch.set_printoptions(precision=10)

In [85]:
model = nn.Linear(1, 1)

In [86]:
model.weight, model.bias

(Parameter containing:
 tensor([[0.4594646692]], requires_grad=True),
 Parameter containing:
 tensor([0.5336952209], requires_grad=True))

In [87]:
x = tensor([2.0])
y_true = tensor([0.5])
y_pred = model(x)
y_pred

tensor([1.4526245594], grad_fn=<ViewBackward0>)

In [88]:
loss = loss_fn(y_pred, y_true)
loss

tensor(0.9074935317, grad_fn=<MseLossBackward0>)

In [89]:
model.weight.grad, model.bias.grad

(None, None)

In [90]:
for layer in model.parameters():
    print(layer)

Parameter containing:
tensor([[0.4594646692]], requires_grad=True)
Parameter containing:
tensor([0.5336952209], requires_grad=True)


In [91]:
optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

In [92]:
loss.backward()

In [93]:
model.weight.grad, model.bias.grad

(tensor([[3.8104982376]]), tensor([1.9052491188]))

In [94]:
model.weight, model.bias

(Parameter containing:
 tensor([[0.4594646692]], requires_grad=True),
 Parameter containing:
 tensor([0.5336952209], requires_grad=True))

In [95]:
optimizer.step()

In [96]:
model.weight, model.bias

(Parameter containing:
 tensor([[0.4213596880]], requires_grad=True),
 Parameter containing:
 tensor([0.5146427155], requires_grad=True))

In [97]:
model.weight.grad, model.bias.grad

(tensor([[3.8104982376]]), tensor([1.9052491188]))

In [98]:
optimizer.zero_grad()

In [99]:
model.weight.grad, model.bias.grad

(None, None)

In [ ]:
0.4594646692 -> 0.4213596880

In [80]:
# param_new = param_old - lr * grad

In [100]:
0.4594646692 - 0.01 * 3.8104982376

0.421359686824

In [101]:
0.5336952209 - 0.01 * 1.9052491188

0.514642729712

### Class

In [103]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(5, 1)

    def forward(self, x):
        return self.layer(x)

In [104]:
model = MyModel()

In [107]:
total_params = sum(p.numel() for p in model.parameters())
total_params

6

In [105]:
x = tensor([1.0, 2.0, 3.0, 4.0, 5.0])
y = model(x)

In [106]:
y

tensor([0.3804801702], grad_fn=<ViewBackward0>)

In [108]:
model

MyModel(
  (layer): Linear(in_features=5, out_features=1, bias=True)
)

In [113]:
class MyModel(nn.Module):
    def __init__(self, n_layers=1):
        super().__init__()

        layers = []

        for _ in range(n_layers - 1):
            layers.append(nn.Linear(5, 5))

        layers.append(nn.Linear(5, 1))

        self.layers = nn.Sequential(*layers)

    def forward(self, x):
        return self.layers(x)

In [114]:
model = MyModel(n_layers=1)

In [115]:
model

MyModel(
  (layers): Sequential(
    (0): Linear(in_features=5, out_features=1, bias=True)
  )
)

In [116]:
total_params = sum(p.numel() for p in model.parameters())
total_params

6

In [117]:
model = MyModel(n_layers=100)

In [118]:
total_params = sum(p.numel() for p in model.parameters())
total_params

2976

In [120]:
# model