In [1]:
from torch import tensor, nn
import torch

### Seed

In [2]:
torch.manual_seed(42)

In [3]:
model = nn.Linear(1,1)

In [4]:
# New
model.weight, model.bias

(Parameter containing:
 tensor([[0.7645]], requires_grad=True),
 Parameter containing:
 tensor([0.8300], requires_grad=True))

In [5]:
# Old
model.weight, model.bias

(Parameter containing:
 tensor([[0.7645]], requires_grad=True),
 Parameter containing:
 tensor([0.8300], requires_grad=True))

### Hardcoded

In [5]:
model = nn.Linear(1,1)
model.load_state_dict({
    "weight": torch.tensor([[0.7645]]),
    "bias": torch.tensor([0.8300])
})

<All keys matched successfully>

In [6]:
model.weight, model.bias

(Parameter containing:
 tensor([[0.7645]], requires_grad=True),
 Parameter containing:
 tensor([0.8300], requires_grad=True))

### Save & Load

In [7]:
model.state_dict()

OrderedDict([('weight', tensor([[0.7645]])), ('bias', tensor([0.8300]))])

In [8]:
torch.save(model.state_dict(), "model.pth")

In [9]:
state_dict = torch.load("model.pth")

In [10]:
state_dict

OrderedDict([('weight', tensor([[0.7645]])), ('bias', tensor([0.8300]))])

In [11]:
new_model = nn.Linear(1,1)
new_model.load_state_dict(state_dict)

<All keys matched successfully>

In [12]:
new_model = nn.Linear(2,1)
new_model.load_state_dict(state_dict)

RuntimeError: Error(s) in loading state_dict for Linear:
	size mismatch for weight: copying a param with shape torch.Size([1, 1]) from checkpoint, the shape in current model is torch.Size([1, 2]).

### Other Configs

In [13]:
model = nn.Linear(1,1, bias=False)

In [14]:
model.weight, model.bias

(Parameter containing:
 tensor([[-0.7336]], requires_grad=True),
 None)

In [26]:
model = nn.Linear(10000,1, bias=False)

In [27]:
model.weight[:10]

tensor([[-0.0003,  0.0078,  0.0096,  ...,  0.0096,  0.0056, -0.0091]],
       grad_fn=<SliceBackward0>)

In [29]:
model.weight.mean(), model.weight.std()

(tensor(0.0123, grad_fn=<MeanBackward0>),
 tensor(0.9914, grad_fn=<StdBackward0>))

In [32]:
nn.init.normal_(model.weight, mean=0.0, std=4)
pass

In [33]:
model.weight.mean(), model.weight.std()

(tensor(-0.0354, grad_fn=<MeanBackward0>),
 tensor(3.9884, grad_fn=<StdBackward0>))