In [1]:
from torch import tensor, nn
import torch

### 1 Layer

In [2]:
model = nn.Linear(1,1, bias = False)
model.load_state_dict({
    "weight": torch.tensor([[1]]),
})

<All keys matched successfully>

In [3]:
model.weight

Parameter containing:
tensor([[1.]], requires_grad=True)

In [4]:
loss_fn = nn.MSELoss()

In [5]:
x = tensor([10.0])
y_true = tensor([15.0])
y_pred = model(x)
y_pred

tensor([10.], grad_fn=<SqueezeBackward4>)

In [10]:
loss = loss_fn(y_pred, y_true)
loss

tensor(25., grad_fn=<MseLossBackward0>)

In [7]:
loss.backward()

In [8]:
model.weight.grad

tensor([[-100.]])

In [ ]:
# grad = dl/dw -> dL_dw

In [13]:
2 * (10 - 15) * 10

-100

In [15]:
model = nn.Linear(1,1, bias = False)
model.load_state_dict({
    "weight": torch.tensor([[1]]),
})

x = tensor([7.0])
y_true = tensor([15.0])
y_pred = model(x)
loss = loss_fn(y_pred, y_true)
loss.backward()
model.weight.grad

tensor([[-112.]])

In [16]:
2 * (7 - 15) * 7

-112

In [17]:
model = nn.Linear(1,1, bias = False)
model.load_state_dict({
    "weight": torch.tensor([[3]]),
})

x = tensor([7.0])
y_true = tensor([15.0])
y_pred = model(x)
loss = loss_fn(y_pred, y_true)
loss.backward()
model.weight.grad

tensor([[84.]])

In [18]:
y_pred

tensor([21.], grad_fn=<SqueezeBackward4>)

In [19]:
2 * (21 - 15) * 7

84

### > 1 layer

In [25]:
model = nn.Sequential(
    nn.Linear(1, 1, bias = False),
    nn.Linear(1, 1, bias = False),
)

model.load_state_dict({
    "0.weight": torch.tensor([[2.0]]),
    "1.weight": torch.tensor([[3.0]]),
})

<All keys matched successfully>

In [26]:
model[0].weight, model[1].weight

(Parameter containing:
 tensor([[2.]], requires_grad=True),
 Parameter containing:
 tensor([[3.]], requires_grad=True))

In [27]:
x = tensor([7.0])
y_true = tensor([15.0])
y_pred = model(x)
loss = loss_fn(y_pred, y_true)
loss.backward()

In [30]:
y_pred

tensor([42.], grad_fn=<SqueezeBackward4>)

In [29]:
model[0].weight.grad, model[1].weight.grad

(tensor([[1134.]]), tensor([[756.]]))

In [31]:
2 * (42 - 15) * 7 * 2

756

In [32]:
2 * (42 - 15) * 7 * 3

1134