In [21]:
import torch
from torch import nn, tensor

In [22]:
lin = nn.Linear(2, 1)

lin.load_state_dict({
    "weight": torch.tensor([[0.1, 0.3]]),
    "bias": torch.tensor([-0.5]),
})

<All keys matched successfully>

In [23]:
x = torch.tensor([[1.0, 2.0]])
y = lin(x)

In [24]:
y

tensor([[0.2000]], grad_fn=<AddmmBackward0>)

In [25]:
def custom_loss(y):
    if y > 0:
        loss = torch.abs(y**3 - 5)
    else:
        loss = torch.abs(y**0.5 - 2)
    return loss

In [26]:
loss = custom_loss(y)
loss

tensor([[4.9920]], grad_fn=<AbsBackward0>)

In [27]:
loss.backward()

In [28]:
lin.weight.grad, lin.bias.grad

(tensor([[-0.1200, -0.2400]]), tensor([-0.1200]))

In [29]:
dL_dy = - 3 * (y.item()) ** 2
dy_dweight1 = x[0][0]
dy_dweight2 = x[0][1]
dy_dbias = 1

dL_dweight1 = dL_dy * dy_dweight1
dL_dweight2 = dL_dy * dy_dweight2
dL_dbias = dL_dy * dy_dbias

In [30]:
dL_dweight1, dL_dweight2, dL_dbias

(tensor(-0.1200), tensor(-0.2400), -0.1200000572204658)